"""The chain-linker's safe-prefix watermark (CR-2, doc 12 §4.4).

Pure, session-free logic: given the current transaction snapshot, the visible ``audit_event`` ids
just above the linker's watermark, and the persisted stall marker, decide how far the chain may
safely be linked THIS tick — and update the stall marker. Concentrating all the correctness here
(boundary / in-flight-gap / rollback-gap / dense cases) keeps it unit-testable without a DB.

Why this exists. ``audit_event.id`` is allocated at INSERT (an IDENTITY sequence) but a row becomes
visible only at COMMIT, and the ack/review sweeps hold ONE long transaction that commits a whole
batch of already-allocated audit rows at the end. So a *higher* id from a short txn can commit and
get linked *before* a *lower* id still uncommitted in a sweep — and ``verify_chain``'s strict
id-order walk (which we must NOT change — it is what detects reorders) then reports a permanent,
unrepairable false tamper break. The linker therefore links each org's rows in id order only up to a
**safe watermark** ``W`` = the highest id such that every id ≤ W is DECIDED (committed-and-visible,
or permanently rolled back).

Gaps. A gap in the id sequence below a visible id is either an in-flight allocation (its txn
is still open — the row is coming and MUST be linked in order) or a permanent rollback (its txn
aborted — we MUST advance past it, else one aborted audit txn halts the chain forever). Time cannot
distinguish them (a long txn can commit after any grace — the report's trap (b)). The proof that a
gap is a rollback is transactional: record ``pg_snapshot_xmax`` when we first stall at the gap; on a
later tick, once ``pg_snapshot_xmin`` has reached that xmax, EVERY txn that could own the gap has
ended (the gap was allocated before the stall — a higher id was already visible — so its owner was
running-or-ended then, i.e. had an xid < that xmax), and the id is still absent, so it was rolled
back. This is time-agnostic and never compares a row's xid to its id (the report's trap ⚠). Snapshot
xids are ``xid8`` (64-bit, monotonic, wraparound-free), so the ``xmin ≥ xmax`` compare is a plain
integer compare.

⚠ PRECONDITION (why the ``xmin ≥ xmax`` proof is sound HERE). It relies on a gap id's owning txn
having acquired an xid *below* the recorded ``stall_xmax`` — i.e. before a higher id became visible.
That holds because ``audit_event.id`` is ``GENERATED ALWAYS AS IDENTITY`` and every audit row is
written by the INSERT that draws the identity value — the *same statement* that stamps the tuple's
xid — so id allocation and xid acquisition are inseparable (and in practice the writing unit of work
already holds an xid from an earlier write). PostgreSQL *does* assign xids lazily and an identity
value CAN be consumed before a txn has an xid — but only via a bare ``nextval`` NOT followed by the
heap insert in the same statement, held open across a linker tick. This codebase never does that:
there is no ``nextval`` / ``OVERRIDING SYSTEM VALUE`` anywhere — ids are server-generated by the
INSERT (grep-guarded). If that ever changes, this proof must be revisited.
"""

from __future__ import annotations

import dataclasses


@dataclasses.dataclass(frozen=True, slots=True)
class WatermarkState:
    """The linker's persisted cursor. ``stall_xmax``/``stall_ceiling`` are set together (a pending
    rollback-vs-in-flight gap under observation) or both ``None`` (no gap pending)."""

    watermark: int
    stall_xmax: int | None
    stall_ceiling: int | None


@dataclasses.dataclass(frozen=True, slots=True)
class WatermarkStep:
    """The result of one tick: the new persisted ``state`` and ``link_up_to`` — the id through which
    the linker links each org's visible rows in id order (always == ``state.watermark``)."""

    state: WatermarkState
    link_up_to: int


def advance_watermark(
    prior: WatermarkState,
    *,
    ids_above: list[int],
    snap_xmin: int,
    snap_xmax: int,
) -> WatermarkStep:
    """Advance the safe watermark one tick. ``ids_above`` are the visible ``audit_event`` ids with
    ``id > prior.watermark``, ascending — a bounded window (the linker re-fetches from the new
    watermark next tick, so a partial window just means "continue next tick"). Includes ALREADY-
    CHAINED ids (they occupy the id space); the linker still only links the unchained ones ≤ W."""
    w = prior.watermark
    if not ids_above:
        # Nothing visible above the watermark → nothing to link, no gap to reason about.
        return WatermarkStep(WatermarkState(w, None, None), link_up_to=w)

    # The contiguous (gap-free) run of visible ids starting at w+1.
    dense_end = w
    for i in ids_above:
        if i == dense_end + 1:
            dense_end = i
        else:
            break

    max_seen = ids_above[-1]
    if dense_end == max_seen:
        # The whole window is contiguous from w+1 — no gap SEEN below a visible id. Advance over it
        # and clear any stall (a previously-pending gap has since committed into this dense run). A
        # gap may lurk just beyond a full window, but that is next tick's observation.
        return WatermarkStep(WatermarkState(dense_end, None, None), link_up_to=dense_end)

    # A gap sits at dense_end+1: it is below max_seen (a higher id is already visible), so it was
    # allocated before now and is either in-flight or rolled back.
    if prior.stall_xmax is not None and snap_xmin >= prior.stall_xmax:
        # PROOF holds: every txn running when the stall was recorded has ended. Every id ≤
        # stall_ceiling was allocated by then, so any still-absent one is a rollback — advance past
        # the whole batch to the recorded ceiling (the dense run cannot exceed it while a gap ≤ it
        # remains, but take the max defensively) and re-observe above it next tick.
        advanced = max(dense_end, prior.stall_ceiling or dense_end)
        return WatermarkStep(WatermarkState(advanced, None, None), link_up_to=advanced)

    # First sight of a gap (no stall yet), or a gap that moved ABOVE the recorded ceiling → record a
    # FRESH stall (xmax now, ceiling = the highest id we can see). Otherwise KEEP the existing stall
    # unchanged — resetting its xmax every tick would move the goalpost so xmin never catches it and
    # the linker would wait forever. Either way, advance W over the confirmed dense prefix and wait.
    keep = (
        prior.stall_xmax is not None
        and prior.stall_ceiling is not None
        and dense_end + 1 <= prior.stall_ceiling
    )
    return WatermarkStep(
        WatermarkState(
            dense_end,
            prior.stall_xmax if keep else snap_xmax,
            prior.stall_ceiling if keep else max_seen,
        ),
        link_up_to=dense_end,
    )
