"""The frozen ISO 9001:2015 clause catalog — reviewable seed data (slice S9, doc 02 §2).

The authoritative source for the ``clause`` reference table seeded by migration
``0018_seed_clauses``. Authored from doc 02 §2 (the clause-by-clause walkthrough), §2.1 (the ★
mandatory documented-information set, Register R30 — exactly 20 rows incl. 8.5.6), and §3.2 (the
PDCA↔clause mapping; clause 7 is split across PLAN and DO). Drafted and adversarially verified
against doc 02 before freezing (two corrections: 7.5 is not a §2.1 ★ row; 5.1.1's official title is
"General"). Kept as a data module (not inline in the migration) so it is reviewable and unit-testable
(``tests/unit/test_clause_catalog.py``) and a single source of truth for any future re-seed.

Each tuple: ``(number, parent_number, title, intent_text, is_mandatory_star, pdca_phase,
requirement_node)``. ``parent_number`` is ``None`` for the seven top-level clauses (4..10);
``pdca_phase`` is one of PLAN/DO/CHECK/ACT.
"""
# Frozen ISO-text reference data: the official clause titles/intents carry em-dashes and run long.
# ruff: noqa: E501, RUF001

from __future__ import annotations

CLAUSES: tuple[tuple[str, str | None, str, str, bool, str, bool], ...] = (
    (
        "4",
        None,
        "Context of the Organization",
        "Establish why the QMS exists and what it covers — the external/internal context, interested parties, scope, and the process landscape. Section header for clauses 4.1–4.4.",
        False,
        "PLAN",
        False,
    ),
    (
        "4.1",
        "4",
        "Understanding the organization and its context",
        "Determine the external and internal issues relevant to the QMS purpose and strategic direction, and monitor/review information about them.",
        False,
        "PLAN",
        True,
    ),
    (
        "4.2",
        "4",
        "Understanding the needs and expectations of interested parties",
        "Identify the interested parties relevant to the QMS and their requirements, and monitor/review them.",
        False,
        "PLAN",
        True,
    ),
    (
        "4.3",
        "4",
        "Determining the scope of the quality management system",
        "Define and document the boundaries and applicability of the QMS, including any justified exclusions. A mandatory maintained document.",
        True,
        "PLAN",
        True,
    ),
    (
        "4.4",
        "4",
        "Quality management system and its processes",
        "Establish, implement, maintain and continually improve the QMS and the processes needed — their sequence, interaction, criteria, and methods. A mandatory maintained document.",
        True,
        "PLAN",
        True,
    ),
    (
        "4.4.1",
        "4.4",
        "Quality management system and its processes (determination of processes)",
        "Determine the processes needed for the QMS and their application: inputs/outputs, sequence and interaction, criteria, resources, responsibilities, risks and opportunities.",
        False,
        "PLAN",
        True,
    ),
    (
        "4.4.2",
        "4.4",
        "Quality management system and its processes (documented information)",
        "Maintain documented information to support process operation and retain documented information to have confidence the processes are carried out as planned.",
        False,
        "PLAN",
        True,
    ),
    (
        "5",
        None,
        "Leadership",
        "Top-management commitment, the Quality Policy, and assignment of organizational roles, responsibilities and authorities. Section header for clauses 5.1–5.3.",
        False,
        "PLAN",
        False,
    ),
    (
        "5.1",
        "5",
        "Leadership and commitment",
        "Top management demonstrates leadership and commitment to the QMS and to customer focus. Section header covering 5.1.1 and 5.1.2.",
        False,
        "PLAN",
        True,
    ),
    (
        "5.1.1",
        "5.1",
        "General",
        "Top management takes accountability for QMS effectiveness, integrates requirements into business processes, and promotes the process approach and risk-based thinking.",
        False,
        "PLAN",
        True,
    ),
    (
        "5.1.2",
        "5.1",
        "Customer focus",
        "Top management ensures customer and applicable regulatory requirements are determined and met, and that customer-satisfaction risks and opportunities are addressed.",
        False,
        "PLAN",
        True,
    ),
    (
        "5.2",
        "5",
        "Policy",
        "Establish, implement and maintain the Quality Policy and make it available as documented information. A mandatory maintained document, at the apex of the document hierarchy.",
        True,
        "PLAN",
        True,
    ),
    (
        "5.2.1",
        "5.2",
        "Establishing the quality policy",
        "Top management establishes a Quality Policy appropriate to the organization, providing a framework for quality objectives and a commitment to satisfy requirements and continually improve.",
        False,
        "PLAN",
        True,
    ),
    (
        "5.2.2",
        "5.2",
        "Communicating the quality policy",
        "Make the Quality Policy available and maintained as documented information, communicate it within the organization, and make it available to interested parties as appropriate.",
        False,
        "PLAN",
        True,
    ),
    (
        "5.3",
        "5",
        "Organizational roles, responsibilities and authorities",
        "Top management assigns, communicates and ensures understanding of roles, responsibilities and authorities relevant to the QMS. Feeds the RACI matrix and the permission layer.",
        False,
        "PLAN",
        True,
    ),
    (
        "6",
        None,
        "Planning",
        "Risk-based thinking, quality objectives, and the planning of changes. Section header for clauses 6.1–6.3.",
        False,
        "PLAN",
        False,
    ),
    (
        "6.1",
        "6",
        "Actions to address risks and opportunities",
        "Determine the risks and opportunities that need to be addressed and plan actions to address them, integrating those actions into QMS processes and evaluating their effectiveness.",
        False,
        "PLAN",
        True,
    ),
    (
        "6.2",
        "6",
        "Quality objectives and planning to achieve them",
        "Establish measurable quality objectives consistent with the Quality Policy and plan how to achieve them. Mandatory documented information, measurable by construction.",
        True,
        "PLAN",
        True,
    ),
    (
        "6.3",
        "6",
        "Planning of changes",
        "When changes to the QMS are needed, carry them out in a planned manner — considering purpose, integrity, resources, and the allocation of responsibilities and authorities.",
        False,
        "PLAN",
        True,
    ),
    (
        "7",
        None,
        "Support",
        "Resources, competence, awareness, communication, and the control of documented information itself. Section header for clauses 7.1–7.5; split across PLAN (resourcing) and DO (operating/document control).",
        False,
        "PLAN",
        False,
    ),
    (
        "7.1",
        "7",
        "Resources",
        "Determine and provide the resources needed for the QMS. Section header covering people, infrastructure, environment, monitoring/measuring resources, and organizational knowledge.",
        False,
        "PLAN",
        True,
    ),
    (
        "7.1.1",
        "7.1",
        "General",
        "Consider the capabilities and constraints of existing internal resources and what is needed from external providers when determining and providing QMS resources.",
        False,
        "PLAN",
        True,
    ),
    (
        "7.1.2",
        "7.1",
        "People",
        "Determine and provide the people necessary for the effective implementation of the QMS and the operation and control of its processes.",
        False,
        "PLAN",
        True,
    ),
    (
        "7.1.3",
        "7.1",
        "Infrastructure",
        "Determine, provide and maintain the infrastructure (buildings, equipment, transport, ICT) needed for process operation and conformity of products and services.",
        False,
        "PLAN",
        True,
    ),
    (
        "7.1.4",
        "7.1",
        "Environment for the operation of processes",
        "Determine, provide and maintain the environment (social, psychological, physical factors) necessary for process operation and product/service conformity.",
        False,
        "PLAN",
        True,
    ),
    (
        "7.1.5",
        "7.1",
        "Monitoring and measuring resources",
        "Determine and provide the resources needed to ensure valid and reliable monitoring and measurement results. Section header covering 7.1.5.1 and 7.1.5.2.",
        False,
        "PLAN",
        True,
    ),
    (
        "7.1.5.1",
        "7.1.5",
        "General",
        "Ensure monitoring and measuring resources are suitable, maintained, and fit for purpose; retain documented evidence of their fitness. Mandatory retained record.",
        True,
        "PLAN",
        True,
    ),
    (
        "7.1.5.2",
        "7.1.5",
        "Measurement traceability",
        "Where traceability is a requirement, calibrate or verify measuring equipment against traceable standards and retain the calibration basis as documented information. Mandatory retained record.",
        True,
        "PLAN",
        True,
    ),
    (
        "7.1.6",
        "7.1",
        "Organizational knowledge",
        "Determine the knowledge necessary for process operation and conformity, maintain it, and make it available; acquire additional knowledge to address changing needs.",
        False,
        "PLAN",
        True,
    ),
    (
        "7.2",
        "7",
        "Competence",
        "Determine and ensure the competence of persons affecting QMS performance and retain documented information as evidence of competence (education, training, skills, experience). Mandatory retained record.",
        True,
        "PLAN",
        True,
    ),
    (
        "7.3",
        "7",
        "Awareness",
        "Ensure persons are aware of the Quality Policy, relevant quality objectives, their contribution to QMS effectiveness, and the implications of nonconformity.",
        False,
        "PLAN",
        True,
    ),
    (
        "7.4",
        "7",
        "Communication",
        "Determine the internal and external communications relevant to the QMS — what, when, with whom, how, and who communicates.",
        False,
        "PLAN",
        True,
    ),
    (
        "7.5",
        "7",
        "Documented information",
        "The meta-clause governing control of documented information; EasySynQ implements this as its core control engine rather than storing it as a document. Section header for 7.5.1–7.5.3.",
        False,
        "DO",
        True,
    ),
    (
        "7.5.1",
        "7.5",
        "General",
        "The QMS includes the documented information required by the standard and that the organization determines necessary for QMS effectiveness.",
        False,
        "DO",
        True,
    ),
    (
        "7.5.2",
        "7.5",
        "Creating and updating",
        "When creating and updating documented information, ensure appropriate identification, description, format and media, and review and approval for suitability and adequacy. Maps to document metadata and the approval workflow.",
        False,
        "DO",
        True,
    ),
    (
        "7.5.3",
        "7.5",
        "Control of documented information",
        "Control documented information for availability, protection, distribution, access, storage, version control, retention and disposition. Maps to the controlled vault, immutable versions, check-in/out, access control and retention policies.",
        False,
        "DO",
        True,
    ),
    (
        "8",
        None,
        "Operation",
        "The actual doing — operational planning, customer requirements, design, suppliers, production/service, release, and control of nonconforming outputs. Section header for clauses 8.1–8.7.",
        False,
        "DO",
        False,
    ),
    (
        "8.1",
        "8",
        "Operational planning and control",
        "Plan, implement and control the processes needed to meet product/service requirements; determine criteria and retain documented information giving confidence processes were carried out as planned. Mandatory documented information.",
        True,
        "DO",
        True,
    ),
    (
        "8.2",
        "8",
        "Requirements for products and services",
        "Customer communication and the determination and review of requirements for products and services. Section header covering 8.2.1–8.2.4.",
        False,
        "DO",
        True,
    ),
    (
        "8.2.1",
        "8.2",
        "Customer communication",
        "Communicate with customers about products/services, enquiries and orders, customer feedback (including complaints), customer property, and contingency actions. Includes complaint intake.",
        False,
        "DO",
        True,
    ),
    (
        "8.2.2",
        "8.2",
        "Determining the requirements for products and services",
        "Determine the requirements (including statutory/regulatory and organization-determined) for products and services offered to customers, ensuring claims can be met.",
        False,
        "DO",
        True,
    ),
    (
        "8.2.3",
        "8.2",
        "Review of the requirements for products and services",
        "Review the ability to meet requirements before committing to supply, and retain documented information on the results of the review and any new requirements. Mandatory retained record.",
        True,
        "DO",
        True,
    ),
    (
        "8.2.3.1",
        "8.2.3",
        "Review of the requirements for products and services (conduct of review)",
        "Before committing to supply, review customer-stated, delivery/post-delivery, organization-specified, statutory/regulatory, and differing contract requirements.",
        False,
        "DO",
        True,
    ),
    (
        "8.2.3.2",
        "8.2.3",
        "Review of the requirements for products and services (documented information)",
        "Retain documented information on the results of the review and on any new requirements for the products and services.",
        False,
        "DO",
        True,
    ),
    (
        "8.2.4",
        "8.2",
        "Changes to requirements for products and services",
        "Ensure relevant documented information is amended and relevant persons made aware when requirements for products and services change.",
        False,
        "DO",
        True,
    ),
    (
        "8.3",
        "8",
        "Design and development of products and services",
        "Establish, implement and maintain a design and development process; retain documented information on inputs, controls, outputs and changes. Mandatory retained records (hideable when excluded per 4.3).",
        True,
        "DO",
        True,
    ),
    (
        "8.3.1",
        "8.3",
        "General",
        "Establish, implement and maintain a design and development process appropriate to ensure subsequent provision of products and services.",
        False,
        "DO",
        True,
    ),
    (
        "8.3.2",
        "8.3",
        "Design and development planning",
        "Determine the stages and controls for design and development considering nature, duration, complexity, required process stages, verification/validation, responsibilities, resources, and documented information needs.",
        False,
        "DO",
        True,
    ),
    (
        "8.3.3",
        "8.3",
        "Design and development inputs",
        "Determine the requirements essential for the specific types of products/services being designed, and retain documented information on design and development inputs.",
        False,
        "DO",
        True,
    ),
    (
        "8.3.4",
        "8.3",
        "Design and development controls",
        "Apply controls to the design process — define results, conduct reviews, verification and validation activities — and retain documented information of these activities.",
        False,
        "DO",
        True,
    ),
    (
        "8.3.5",
        "8.3",
        "Design and development outputs",
        "Ensure design outputs meet input requirements, are adequate for subsequent provision, and reference monitoring/acceptance criteria; retain documented information on outputs.",
        False,
        "DO",
        True,
    ),
    (
        "8.3.6",
        "8.3",
        "Design and development changes",
        "Identify, review and control changes to design and development to ensure no adverse impact on conformity; retain documented information on changes, results, authorizations and actions.",
        False,
        "DO",
        True,
    ),
    (
        "8.4",
        "8",
        "Control of externally provided processes, products and services",
        "Ensure externally provided processes, products and services conform to requirements; evaluate, select, monitor and re-evaluate external providers and retain documented information. Mandatory retained records.",
        True,
        "DO",
        True,
    ),
    (
        "8.4.1",
        "8.4",
        "General",
        "Determine controls for externally provided processes, products and services (including outsourced processes), and evaluate/select/monitor providers based on their ability to meet requirements; retain the evaluation evidence.",
        False,
        "DO",
        True,
    ),
    (
        "8.4.2",
        "8.4",
        "Type and extent of control",
        "Ensure externally provided processes/products/services do not adversely affect conformity; define the controls applied to external providers and to their outputs.",
        False,
        "DO",
        True,
    ),
    (
        "8.4.3",
        "8.4",
        "Information for external providers",
        "Communicate requirements to external providers regarding processes/products/services, approvals, competence, interactions, control/monitoring, and verification activities.",
        False,
        "DO",
        True,
    ),
    (
        "8.5",
        "8",
        "Production and service provision",
        "Implement production and service provision under controlled conditions. Section header covering 8.5.1–8.5.6.",
        False,
        "DO",
        True,
    ),
    (
        "8.5.1",
        "8.5",
        "Control of production and service provision",
        "Provide products and services under controlled conditions: availability of documented information, monitoring/measuring resources, competent persons, validated processes, and release/delivery activities.",
        False,
        "DO",
        True,
    ),
    (
        "8.5.2",
        "8.5",
        "Identification and traceability",
        "Identify outputs to ensure conformity and, where traceability is a requirement, control the unique identification and retain the documented information needed for traceability. Mandatory retained record.",
        True,
        "DO",
        True,
    ),
    (
        "8.5.3",
        "8.5",
        "Property belonging to customers or external providers",
        "Exercise care with property belonging to customers or external providers; when property is lost/damaged/unusable, report to the owner and retain documented information on what occurred. Mandatory retained record.",
        True,
        "DO",
        True,
    ),
    (
        "8.5.4",
        "8.5",
        "Preservation",
        "Preserve outputs during production and service provision to the extent necessary to maintain conformity (e.g., identification, handling, contamination control, packaging, storage, protection).",
        False,
        "DO",
        True,
    ),
    (
        "8.5.5",
        "8.5",
        "Post-delivery activities",
        "Meet requirements for post-delivery activities (warranties, maintenance, recycling, final disposal), considering risks, customer feedback and statutory/regulatory requirements.",
        False,
        "DO",
        True,
    ),
    (
        "8.5.6",
        "8.5",
        "Control of changes",
        "Review and control changes for production or service provision to ensure continuing conformity; retain documented information describing the change, its review results, the authorizing person, and necessary actions. Mandatory retained record (R30).",
        True,
        "DO",
        True,
    ),
    (
        "8.6",
        "8",
        "Release of products and services",
        "Verify that product/service requirements have been met before release; retain documented information on the evidence of conformity and the person(s) authorizing release. Mandatory retained record.",
        True,
        "DO",
        True,
    ),
    (
        "8.7",
        "8",
        "Control of nonconforming outputs",
        "Identify and control outputs that do not conform to requirements to prevent unintended use/delivery; retain documented information describing the nonconformity, actions taken, concessions, and the deciding authority. Mandatory retained record.",
        True,
        "DO",
        True,
    ),
    (
        "9",
        None,
        "Performance Evaluation",
        "Monitoring, measurement, analysis and evaluation; internal audit; and management review. Section header for clauses 9.1–9.3.",
        False,
        "CHECK",
        False,
    ),
    (
        "9.1",
        "9",
        "Monitoring, measurement, analysis and evaluation",
        "Determine what needs to be monitored/measured, the methods, and when, then analyze and evaluate the results. Section header covering 9.1.1–9.1.3.",
        False,
        "CHECK",
        True,
    ),
    (
        "9.1.1",
        "9.1",
        "General",
        "Determine and apply monitoring, measurement, analysis and evaluation to ensure valid results and QMS effectiveness; retain documented information as evidence of the results. Mandatory retained record.",
        True,
        "CHECK",
        True,
    ),
    (
        "9.1.2",
        "9.1",
        "Customer satisfaction",
        "Monitor customers' perception of the degree to which their needs and expectations have been fulfilled, and determine methods for obtaining and using this information.",
        False,
        "CHECK",
        True,
    ),
    (
        "9.1.3",
        "9.1",
        "Analysis and evaluation",
        "Analyze and evaluate data and information from monitoring and measurement to assess conformity, customer satisfaction, QMS performance, planning effectiveness, risk actions, providers, and improvement needs.",
        False,
        "CHECK",
        True,
    ),
    (
        "9.2",
        "9",
        "Internal audit",
        "Conduct internal audits at planned intervals; plan, establish, implement and maintain an audit program and retain documented information as evidence of program implementation and audit results. Mandatory maintained plan + retained records.",
        True,
        "CHECK",
        True,
    ),
    (
        "9.2.1",
        "9.2",
        "Internal audit (purpose and conformity)",
        "Conduct internal audits to provide information on whether the QMS conforms to the organization's own requirements and to ISO 9001 and is effectively implemented and maintained.",
        False,
        "CHECK",
        True,
    ),
    (
        "9.2.2",
        "9.2",
        "Internal audit (program requirements)",
        "Plan, establish, implement and maintain audit programs; define criteria and scope, select objective auditors, report results, take correction, and retain documented information as evidence.",
        False,
        "CHECK",
        True,
    ),
    (
        "9.3",
        "9",
        "Management review",
        "Top management reviews the QMS at planned intervals to ensure its continuing suitability, adequacy, effectiveness and alignment with strategic direction. Section header covering 9.3.1–9.3.3.",
        True,
        "CHECK",
        True,
    ),
    (
        "9.3.1",
        "9.3",
        "General",
        "Top management reviews the QMS at planned intervals to ensure its continuing suitability, adequacy, effectiveness and alignment with the organization's strategic direction.",
        False,
        "CHECK",
        True,
    ),
    (
        "9.3.2",
        "9.3",
        "Management review inputs",
        "Plan and conduct management review considering status of prior actions, changes, performance/effectiveness information, resource adequacy, risk/opportunity actions, and improvement opportunities.",
        False,
        "CHECK",
        True,
    ),
    (
        "9.3.3",
        "9.3",
        "Management review outputs",
        "Outputs include decisions and actions on improvement opportunities, QMS change needs, and resource needs; retain documented information as evidence of the results of management reviews. Mandatory retained record.",
        False,
        "CHECK",
        True,
    ),
    (
        "10",
        None,
        "Improvement",
        "Determine and select improvement opportunities, address nonconformity and corrective action, and continually improve the QMS. Section header for clauses 10.1–10.3.",
        False,
        "ACT",
        False,
    ),
    (
        "10.1",
        "10",
        "General",
        "Determine and select opportunities for improvement and implement necessary actions to meet customer requirements and enhance customer satisfaction.",
        False,
        "ACT",
        True,
    ),
    (
        "10.2",
        "10",
        "Nonconformity and corrective action",
        "React to nonconformities, evaluate the need for action to eliminate causes, implement and review corrective action; retain documented information on the nature of nonconformities and actions taken and on the results of any corrective action. Mandatory retained record (R30).",
        True,
        "ACT",
        True,
    ),
    (
        "10.2.1",
        "10.2",
        "Nonconformity and corrective action (reaction and action)",
        "When a nonconformity occurs, react to control and correct it, deal with consequences, evaluate the need to eliminate causes, implement corrective action, and review effectiveness.",
        False,
        "ACT",
        True,
    ),
    (
        "10.2.2",
        "10.2",
        "Nonconformity and corrective action (documented information)",
        "Retain documented information as evidence of the nature of the nonconformities and any subsequent actions taken, and of the results of any corrective action.",
        False,
        "ACT",
        True,
    ),
    (
        "10.3",
        "10",
        "Continual improvement",
        "Continually improve the suitability, adequacy and effectiveness of the QMS, considering analysis/evaluation results and management review outputs to identify needs/opportunities.",
        False,
        "ACT",
        True,
    ),
)
